/**
 * Style Dictionary config for Web platform.
 *
 * Generates CSS custom properties from W3C DTCG tokens.
 * Consumed by creo-ui-web (packages/web).
 *
 * Theme matrix (0.1.0+):
 *   tokens/color/themes/*.json には `color.themes.{theme-id}.*` path の
 *   token を宣言する。custom format `css/creo-ui-themed` は、
 *   - themeId segment を var 名から除去
 *   - Mint Dark を :root default に出力
 *   - 他 7 theme を [data-theme="{id}"] で出力
 *   - fleetstage 後方互換 alias (.dark / [data-theme="dark"] / [data-theme="light"])
 *   - @media (prefers-color-scheme: light) で default dark → mint-light に逆転
 *   を 1 つの tokens.css に concat する。
 *
 *   editor-mode / spacing / radius / shadow / typography は theme 非依存で
 *   :root に 1 回だけ emit。
 */

const DEFAULT_THEME_ID = 'mint-dark'
const LIGHT_ALIAS_THEME_ID = 'mint-light'

/** themed token の var 名は "--color-{残り path をハイフン結合}" */
const themedVarName = (path) => `--color-${path.slice(3).join('-')}`

/** 非 themed token の var 名は "--{path をハイフン結合}" */
const nonThemedVarName = (path) => `--${path.join('-')}`

/**
 * token.$value から CSS 値を render する。DTCG alias ({path}) は var(--...)
 * 参照として emit、それ以外は値をそのまま。
 */
const renderValue = (token) => {
  const original = token.original?.$value ?? token.original?.value
  if (typeof original === 'string' && /^\{[^}]+\}$/.test(original)) {
    const refPath = original.slice(1, -1).split('.')
    return `var(--${refPath.join('-')})`
  }
  return token.$value ?? token.value
}

const renderDescription = (token) => {
  const desc = token.$description
  return desc ? ` /** ${String(desc).replace(/\*\//g, '*\\/')} */` : ''
}

const isThemed = (token) => token.path[0] === 'color' && token.path[1] === 'themes'

/** theme id を path の 3 番目から取得 */
const themeIdOf = (token) => token.path[2]

export default {
  source: ['tokens/**/*.json'],
  hooks: {
    formats: {
      'css/creo-ui-themed': ({ dictionary }) => {
        const commonLines = []
        const themes = {}

        for (const token of dictionary.allTokens) {
          if (isThemed(token)) {
            const tid = themeIdOf(token)
            const line = `  ${themedVarName(token.path)}: ${renderValue(token)};${renderDescription(token)}`
            if (!themes[tid]) themes[tid] = []
            themes[tid].push(line)
          } else {
            const line = `  ${nonThemedVarName(token.path)}: ${renderValue(token)};${renderDescription(token)}`
            commonLines.push(line)
          }
        }

        const defaultLines = themes[DEFAULT_THEME_ID] ?? []
        const lightAliasLines = themes[LIGHT_ALIAS_THEME_ID] ?? []

        const themeBlocks = Object.keys(themes)
          .sort()
          .map((tid) => [`[data-theme="${tid}"] {`, ...themes[tid], '}'].join('\n'))
          .join('\n\n')

        const header = [
          '/**',
          ' * Do not edit directly — generated by Style Dictionary from Creo UI tokens.',
          ' * Source: tokens/**/*.json (DTCG).',
          ' *',
          ' * Default theme: mint-dark (Creo Design System default)',
          ' * Switch theme via `[data-theme="{id}"]` attribute on any ancestor.',
          ' * fleetstage 後方互換: `.dark` / `[data-theme="dark"]` = mint-dark、',
          ' * `[data-theme="light"]` = mint-light。',
          ' */',
          '',
        ].join('\n')

        const rootBlock = [':root {', ...commonLines, ...defaultLines, '}'].join('\n')

        const fleetstageAlias = [
          '/* fleetstage / legacy 後方互換 */',
          '.dark,',
          '[data-theme="dark"] {',
          ...defaultLines,
          '}',
          '',
          '[data-theme="light"] {',
          ...lightAliasLines,
          '}',
        ].join('\n')

        const prefersLight =
          lightAliasLines.length > 0
            ? [
                '/* system が light preference で [data-theme] 未指定なら mint-light に逆転 */',
                '@media (prefers-color-scheme: light) {',
                '  :root:not([data-theme]):not(.dark):not([data-theme="mint-dark"]) {',
                ...lightAliasLines.map((line) => `  ${line}`),
                '  }',
                '}',
              ].join('\n')
            : ''

        return `${header}${rootBlock}\n\n${themeBlocks}\n\n${fleetstageAlias}\n\n${prefersLight}\n`
      },
    },
  },
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'packages/web/dist/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/creo-ui-themed',
        },
      ],
    },
    js: {
      transformGroup: 'js',
      buildPath: 'packages/web/dist/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
        },
        {
          destination: 'tokens.d.ts',
          format: 'typescript/es6-declarations',
        },
      ],
    },
  },
}
