/**
 * Style Dictionary config for Rust platform.
 *
 * Generates Rust const definitions from W3C DTCG tokens.
 * Consumed by creo-ui crate (packages/rust).
 *
 * Theme policy (0.1.0+):
 *   Rust 側は現状 Mint Dark (= Creo Design System default) のみ emit。他 theme は
 *   Phase 3 で要否検討 (ratatui / egui 等、crate 側の theme 概念次第)。
 *   color.$value は "oklch(l c h [/ a])" 文字列なので、transforms/color-utils.js
 *   の oklchStringToHex → hexToRgb255 で Rgb { r, g, b } u8 に変換する。
 */

import { hexToRgb255, oklchStringToHex } from './color-utils.js'

const DEFAULT_THEME_ID = 'mint-dark'

const SCREAMING_SNAKE = (path) =>
  path
    .flatMap((seg) => seg.split(/[-_]/g))
    .map((seg) => seg.toUpperCase())
    .join('_')

const sanitizeIdent = (name) => (/^[0-9]/.test(name) ? `_${name}` : name)

const dimensionToFloat = (value) => {
  if (typeof value === 'number') return value
  const match = String(value).match(/^(-?\d*\.?\d+)(px|pt|rem)?$/)
  if (!match) return null
  const n = Number.parseFloat(match[1])
  const unit = match[2] ?? 'px'
  if (unit === 'rem') return n * 16
  return n
}

const shouldSkipTheme = (path) => {
  if (path[0] !== 'color' || path[1] !== 'themes') return false
  return path[2] !== DEFAULT_THEME_ID
}

const identPath = (path) => {
  if (path[0] === 'color' && path[1] === 'themes') {
    return ['color', ...path.slice(3)]
  }
  return path
}

const colorStringToRgbBytes = (raw) => {
  const str = String(raw)
  if (/^oklch\(/i.test(str)) {
    const hex = oklchStringToHex(str)
    const [r, g, b] = hexToRgb255(hex)
    return { r, g, b }
  }
  if (str.startsWith('#')) {
    const [r, g, b] = hexToRgb255(str)
    return { r, g, b }
  }
  return null
}

export default {
  source: ['tokens/**/*.json'],
  hooks: {
    formats: {
      'rust/creo-ui': ({ dictionary }) => {
        // NOTE: this file is intended to be `include!()`ed into an outer
        // module, so we avoid inner doc comments (`//!`) and inner attributes
        // (`#![...]`) — those are only allowed at the top of a module / crate,
        // not in the middle of one.
        const header = [
          '// Auto-generated by Style Dictionary from Creo UI tokens.',
          '// Do not edit manually — edit tokens/**/*.json instead.',
          `// Theme: ${DEFAULT_THEME_ID} (Creo Design System default).`,
          '',
          '/// 8-bit-per-channel RGB color, suitable for conversion into',
          '/// `ratatui::style::Color::Rgb`, `image::Rgb`, etc.',
          '#[derive(Debug, Clone, Copy, PartialEq, Eq)]',
          'pub struct Rgb {',
          '    pub r: u8,',
          '    pub g: u8,',
          '    pub b: u8,',
          '}',
          '',
          'impl Rgb {',
          '    pub const fn new(r: u8, g: u8, b: u8) -> Self {',
          '        Self { r, g, b }',
          '    }',
          '',
          '    pub const fn as_array(&self) -> [u8; 3] {',
          '        [self.r, self.g, self.b]',
          '    }',
          '}',
          '',
        ].join('\n')

        const lines = []
        for (const token of dictionary.allTokens) {
          if (shouldSkipTheme(token.path)) continue

          const name = sanitizeIdent(SCREAMING_SNAKE(identPath(token.path)))
          const type = token.$type ?? token.type
          const raw = token.$value ?? token.value
          const comment = token.$description
            ? `/// ${String(token.$description).replace(/\n/g, ' ')}\n`
            : ''

          if (type === 'color') {
            const rgb = colorStringToRgbBytes(raw)
            if (rgb) {
              lines.push(
                `${comment}pub const ${name}: Rgb = Rgb::new(${rgb.r}, ${rgb.g}, ${rgb.b});`,
              )
              continue
            }
            // gradient 等 — &str fallback (Phase 3 で検討)
            lines.push(`${comment}pub const ${name}: &str = ${JSON.stringify(String(raw))};`)
            continue
          }
          if (type === 'dimension') {
            const n = dimensionToFloat(raw)
            if (n !== null) {
              lines.push(`${comment}pub const ${name}: f32 = ${n}_f32;`)
              continue
            }
          }
          if (type === 'fontWeight' || type === 'number') {
            lines.push(`${comment}pub const ${name}: f32 = ${Number(raw)}_f32;`)
            continue
          }
          lines.push(`${comment}pub const ${name}: &str = ${JSON.stringify(String(raw))};`)
        }

        return `${header}\n${lines.join('\n')}\n`
      },
    },
  },
  platforms: {
    rust: {
      transforms: ['name/constant'],
      buildPath: 'packages/rust/src/generated/',
      files: [
        {
          destination: 'tokens.rs',
          format: 'rust/creo-ui',
        },
      ],
    },
  },
}
