/**
 * Style Dictionary config for Web platform.
 *
 * Generates CSS custom properties from W3C DTCG tokens.
 * Consumed by creo-ui-web (packages/web).
 *
 * Dark theme variant (CREO-#1 / fleetstage requirement):
 *   `tokens/color/dark/**` に同じ path (color.dark.*) で宣言された token は、
 *   変数名から `dark` segment を抜いた上で dark-only のルールに出力する。
 *   1 つの tokens.css に light / dark を両方含め、3 段の selector で提供する:
 *     1) :root                                  — light (default)
 *     2) .dark, [data-theme="dark"]             — explicit 強制 (fleetstage 流)
 *     3) @media (prefers-color-scheme: dark)
 *          :root:not(.light):not([data-theme="light"])
 *                                                — system preference 追従
 *   explicit な light 指定があれば (3) はバイパスされる。
 */

const DARK_SEGMENT = 'dark'

/** token.path から DARK_SEGMENT を除いて CSS 変数名を作る */
const varName = (path) => `--${path.filter((seg) => seg !== DARK_SEGMENT).join('-')}`

/**
 * `outputReferences: true` 相当を手書きで: token.original.$value が DTCG alias
 * ({color.brand.primary-subtle}) なら `var(--color-brand-primary-subtle)` として
 * emit、通常値はそのまま emit する。
 */
const renderValue = (token) => {
  const original = token.original?.$value ?? token.original?.value
  if (typeof original === 'string' && /^\{[^}]+\}$/.test(original)) {
    const refPath = original.slice(1, -1).split('.')
    return `var(--${refPath.filter((seg) => seg !== DARK_SEGMENT).join('-')})`
  }
  return token.$value ?? token.value
}

const renderDescription = (token) => {
  const desc = token.$description
  return desc ? ` /** ${String(desc).replace(/\*\//g, '*\\/')} */` : ''
}

export default {
  source: ['tokens/**/*.json'],
  hooks: {
    formats: {
      'css/creo-ui-with-dark': ({ dictionary }) => {
        const lightLines = []
        const darkLines = []
        for (const token of dictionary.allTokens) {
          const isDark = token.path.includes(DARK_SEGMENT)
          const line = `  ${varName(token.path)}: ${renderValue(token)};${renderDescription(token)}`
          if (isDark) {
            darkLines.push(line)
          } else {
            lightLines.push(line)
          }
        }

        const header = [
          '/**',
          ' * Do not edit directly — generated by Style Dictionary from Creo UI tokens.',
          ' * Source: tokens/**/*.json (DTCG).',
          ' */',
          '',
        ].join('\n')

        const lightBlock = [':root {', ...lightLines, '}'].join('\n')

        const darkBlock = darkLines.length
          ? [
              '',
              '/* Explicit dark — .dark class or [data-theme="dark"] */',
              '.dark,',
              '[data-theme="dark"] {',
              ...darkLines,
              '}',
              '',
              '/* System preference dark — consumer が explicit light を宣言していない場合のみ */',
              '@media (prefers-color-scheme: dark) {',
              '  :root:not(.light):not([data-theme="light"]) {',
              ...darkLines.map((line) => `  ${line}`),
              '  }',
              '}',
            ].join('\n')
          : ''

        return `${header}${lightBlock}\n${darkBlock}\n`
      },
    },
  },
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'packages/web/dist/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/creo-ui-with-dark',
        },
      ],
    },
    js: {
      transformGroup: 'js',
      buildPath: 'packages/web/dist/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
        },
        {
          destination: 'tokens.d.ts',
          format: 'typescript/es6-declarations',
        },
      ],
    },
  },
}
