/**
 * Style Dictionary config for Swift (SPM) platform.
 *
 * Generates SwiftUI Color / CGFloat extensions from W3C DTCG tokens.
 * Consumed by CreoUI SPM package (packages/swift).
 *
 * Theme policy (0.1.0+):
 *   tokens/color/themes/*.json には 8 theme 分の token があるが、Swift 側は
 *   現状 Mint Dark (= Creo Design System default) のみ emit する。他 theme は
 *   Phase 3 で Color(dynamicProvider:) + NSAppearance 対応時に追加する。
 *   token.path が `color.themes.*` の場合は mint-dark のみ pick し、
 *   変数名は themes segment を除去する (例: colorBrandPrimaryBase)。
 *
 *   color.$value は "oklch(l c h [/ a])" 文字列で保持されているので、
 *   transforms/color-utils.js の oklchStringToHex → hexToRgb01 で
 *   SwiftUI Color(red, green, blue) に変換する。
 */

import { hexToRgb01, oklchStringToHex, parseOklch } from './color-utils.js'

const DEFAULT_THEME_ID = 'mint-dark'

const camelCase = (path) =>
  path
    .map((seg, i) => {
      const parts = seg.split(/[-_]/g)
      return parts
        .map((p, j) => {
          if (i === 0 && j === 0) return p.toLowerCase()
          return p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()
        })
        .join('')
    })
    .join('')

const sanitizeIdent = (name) => (/^[0-9]/.test(name) ? `_${name}` : name)

const dimensionToFloat = (value) => {
  if (typeof value === 'number') return value
  const match = String(value).match(/^(-?\d*\.?\d+)(px|pt|rem)?$/)
  if (!match) return null
  const n = Number.parseFloat(match[1])
  const unit = match[2] ?? 'px'
  if (unit === 'rem') return n * 16
  return n
}

/** token が themed (color.themes.*) なら default theme 以外は skip */
const shouldSkipTheme = (path) => {
  if (path[0] !== 'color' || path[1] !== 'themes') return false
  return path[2] !== DEFAULT_THEME_ID
}

/** themed token の ident 用 path (themes segment 除去) */
const identPath = (path) => {
  if (path[0] === 'color' && path[1] === 'themes') {
    return ['color', ...path.slice(3)]
  }
  return path
}

/** "#rrggbbaa" の末尾 2 桁から alpha (0-1) を取り出す。無ければ 1 */
const hexAlpha = (hex) => {
  const h = String(hex).replace('#', '')
  if (h.length === 8) return Number.parseInt(h.slice(6, 8), 16) / 255
  return 1
}

/** color $value ("oklch(l c h [/ a])") → { r, g, b, a } in 0-1
 *
 * alpha を必ず持ち回る — 旧実装は hexToRgb01 が alpha を捨てるため、
 * scrim (oklch(0 0 0 / 0.4)) が不透明の純黒として emit されていた
 * (ladyland consumer feedback レビューで発見した #11)。 */
const colorStringToRgba = (raw) => {
  const str = String(raw)
  if (/^oklch\(/i.test(str)) {
    const hex = oklchStringToHex(str)
    const [r, g, b] = hexToRgb01(hex)
    // alpha は hex 経由 (1/255 量子化で 0.5 → 0.502 になる) でなく parse 値をそのまま使う
    const { a } = parseOklch(str)
    return { r, g, b, a: a ?? 1 }
  }
  // fallback: 既存の hex 直値 ("#rrggbb" / "#rrggbbaa")
  if (str.startsWith('#')) {
    const [r, g, b] = hexToRgb01(str)
    return { r, g, b, a: hexAlpha(str) }
  }
  throw new Error(`Unsupported color value for Swift emit: ${str}`)
}

/** duration $value ("80ms" / "0.5s") → 秒 (TimeInterval)。解釈不能なら null */
const durationToSeconds = (raw) => {
  const str = String(raw).trim()
  const ms = str.match(/^(-?\d*\.?\d+)ms$/)
  if (ms) return Number.parseFloat(ms[1]) / 1000
  const s = str.match(/^(-?\d*\.?\d+)s$/)
  if (s) return Number.parseFloat(s[1])
  return null
}

export default {
  source: ['tokens/**/*.json'],
  hooks: {
    formats: {
      'swift/creo-ui': ({ dictionary }) => {
        const header = [
          '//',
          '// Tokens.swift',
          '//',
          '// Auto-generated by Style Dictionary from creo-ui tokens.',
          '// Do not edit manually — edit tokens/**/*.json instead.',
          `// Theme: ${DEFAULT_THEME_ID} (Creo Design System default).`,
          '//',
          '',
          'import SwiftUI',
          'import CoreGraphics',
          'import Foundation',
          '',
        ].join('\n')

        const colors = []
        const dimensions = []
        const numbers = []
        const durations = []
        const strings = []

        for (const token of dictionary.allTokens) {
          if (shouldSkipTheme(token.path)) continue

          const name = sanitizeIdent(camelCase(identPath(token.path)))
          const type = token.$type ?? token.type
          const raw = token.$value ?? token.value
          const comment = token.$description ? ` // ${token.$description}` : ''

          if (type === 'color') {
            try {
              const { r, g, b, a } = colorStringToRgba(raw)
              // alpha 1 のときは opacity 引数を省略 (diff を最小に保つ)
              const opacity = a < 1 ? `, opacity: ${a.toFixed(4)}` : ''
              colors.push(
                `    static let ${name} = Color(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)}${opacity})${comment}`,
              )
            } catch (err) {
              // gradient 等の複合値は一旦 String として emit (Phase 3 で LinearGradient 対応)
              strings.push(
                `    public static let ${name}: String = ${JSON.stringify(String(raw))}${comment}`,
              )
            }
            continue
          }
          if (type === 'duration') {
            const sec = durationToSeconds(raw)
            if (sec !== null) {
              // SwiftUI Animation にそのまま渡せる秒単位 (旧実装は "80ms" の String で
              // 実用不能だった — ladyland consumer feedback #8)
              durations.push(`    public static let ${name}: TimeInterval = ${sec}${comment}`)
              continue
            }
          }
          if (type === 'dimension') {
            const n = dimensionToFloat(raw)
            if (n !== null) {
              dimensions.push(`    public static let ${name}: CGFloat = ${n}${comment}`)
              continue
            }
          }
          if (type === 'fontWeight' || type === 'number') {
            numbers.push(`    public static let ${name}: Double = ${Number(raw)}${comment}`)
            continue
          }
          strings.push(
            `    public static let ${name}: String = ${JSON.stringify(String(raw))}${comment}`,
          )
        }

        const sections = [
          'public extension Color {',
          ...colors,
          '}',
          '',
          'public enum CreoUITokens {',
          ...dimensions,
          ...(dimensions.length && numbers.length ? [''] : []),
          ...numbers,
          ...((dimensions.length || numbers.length) && durations.length ? [''] : []),
          ...durations,
          ...((dimensions.length || numbers.length || durations.length) && strings.length
            ? ['']
            : []),
          ...strings,
          '}',
          '',
        ].join('\n')

        return `${header}\n${sections}`
      },
    },
  },
  platforms: {
    swift: {
      transforms: ['name/camel'],
      buildPath: 'packages/swift/Sources/CreoUI/Generated/',
      files: [
        {
          destination: 'Tokens.swift',
          format: 'swift/creo-ui',
        },
      ],
    },
  },
}
