/**
 * Style Dictionary config for Rust platform.
 *
 * Generates Rust const definitions from W3C DTCG tokens.
 * Consumed by creo-ui crate (packages/rust).
 *
 * NOTE: Style Dictionary has no built-in Rust format.
 * We use a custom format that emits `pub const` definitions.
 * Phase 1 で format を拡張する予定。
 */

export default {
  source: ['tokens/**/*.json'],
  hooks: {
    formats: {
      'rust/consts': ({ dictionary }) => {
        const header = [
          '//! Auto-generated by Style Dictionary from Creo UI tokens.',
          '//! Do not edit manually — edit tokens/**/*.json instead.',
          '',
          '#![allow(dead_code)]',
          '',
        ].join('\n')

        const consts = dictionary.allTokens.map((token) => {
          const name = token.name.toUpperCase().replace(/-/g, '_')
          const value = JSON.stringify(token.value)
          const comment = token.comment ? `/// ${token.comment}\n` : ''
          return `${comment}pub const ${name}: &str = ${value};`
        })

        return `${header}\n${consts.join('\n')}\n`
      },
    },
  },
  platforms: {
    rust: {
      transformGroup: 'js',
      buildPath: 'packages/rust/src/generated/',
      files: [
        {
          destination: 'tokens.rs',
          format: 'rust/consts',
        },
      ],
    },
  },
}
