/**
 * Style Dictionary config for Swift (SPM) platform.
 *
 * Generates SwiftUI Color / CGFloat extensions from W3C DTCG tokens.
 * Consumed by Creoui SPM package (packages/swift).
 *
 * Theme policy (0.1.0+):
 *   tokens/color/themes/*.json には 8 theme 分の token があるが、Swift 側は
 *   現状 Mint Dark (= Creo Design System default) のみ emit する。他 theme は
 *   Phase 3 で Color(dynamicProvider:) + NSAppearance 対応時に追加する。
 *   token.path が `color.themes.*` の場合は mint-dark のみ pick し、
 *   変数名は themes segment を除去する (例: colorBrandPrimaryBase)。
 *
 *   color.$value は "oklch(l c h [/ a])" 文字列で保持されているので、
 *   transforms/color-utils.js の oklchStringToHex → hexToRgb01 で
 *   SwiftUI Color(red, green, blue) に変換する。
 */

import { hexToRgb01, oklchStringToHex } from './color-utils.js'

const DEFAULT_THEME_ID = 'mint-dark'

const camelCase = (path) =>
  path
    .map((seg, i) => {
      const parts = seg.split(/[-_]/g)
      return parts
        .map((p, j) => {
          if (i === 0 && j === 0) return p.toLowerCase()
          return p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()
        })
        .join('')
    })
    .join('')

const sanitizeIdent = (name) => (/^[0-9]/.test(name) ? `_${name}` : name)

const dimensionToFloat = (value) => {
  if (typeof value === 'number') return value
  const match = String(value).match(/^(-?\d*\.?\d+)(px|pt|rem)?$/)
  if (!match) return null
  const n = Number.parseFloat(match[1])
  const unit = match[2] ?? 'px'
  if (unit === 'rem') return n * 16
  return n
}

/** token が themed (color.themes.*) なら default theme 以外は skip */
const shouldSkipTheme = (path) => {
  if (path[0] !== 'color' || path[1] !== 'themes') return false
  return path[2] !== DEFAULT_THEME_ID
}

/** themed token の ident 用 path (themes segment 除去) */
const identPath = (path) => {
  if (path[0] === 'color' && path[1] === 'themes') {
    return ['color', ...path.slice(3)]
  }
  return path
}

/** color $value ("oklch(...)") → { r, g, b } in 0-1 */
const colorStringToRgb = (raw) => {
  const str = String(raw)
  if (/^oklch\(/i.test(str)) {
    const hex = oklchStringToHex(str)
    const [r, g, b] = hexToRgb01(hex)
    return { r, g, b }
  }
  // fallback: 既存の hex 直値 ("#rrggbb")
  if (str.startsWith('#')) {
    const [r, g, b] = hexToRgb01(str)
    return { r, g, b }
  }
  throw new Error(`Unsupported color value for Swift emit: ${str}`)
}

export default {
  source: ['tokens/**/*.json'],
  hooks: {
    formats: {
      'swift/creoui': ({ dictionary }) => {
        const header = [
          '//',
          '// Tokens.swift',
          '//',
          '// Auto-generated by Style Dictionary from creoui tokens.',
          '// Do not edit manually — edit tokens/**/*.json instead.',
          `// Theme: ${DEFAULT_THEME_ID} (Creo Design System default).`,
          '//',
          '',
          'import SwiftUI',
          'import CoreGraphics',
          '',
        ].join('\n')

        const colors = []
        const dimensions = []
        const numbers = []
        const strings = []

        for (const token of dictionary.allTokens) {
          if (shouldSkipTheme(token.path)) continue

          const name = sanitizeIdent(camelCase(identPath(token.path)))
          const type = token.$type ?? token.type
          const raw = token.$value ?? token.value
          const comment = token.$description ? ` // ${token.$description}` : ''

          if (type === 'color') {
            try {
              const { r, g, b } = colorStringToRgb(raw)
              colors.push(
                `    static let ${name} = Color(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)})${comment}`,
              )
            } catch (err) {
              // gradient 等の複合値は一旦 String として emit (Phase 3 で LinearGradient 対応)
              strings.push(
                `    public static let ${name}: String = ${JSON.stringify(String(raw))}${comment}`,
              )
            }
            continue
          }
          if (type === 'dimension') {
            const n = dimensionToFloat(raw)
            if (n !== null) {
              dimensions.push(`    public static let ${name}: CGFloat = ${n}${comment}`)
              continue
            }
          }
          if (type === 'fontWeight' || type === 'number') {
            numbers.push(`    public static let ${name}: Double = ${Number(raw)}${comment}`)
            continue
          }
          strings.push(
            `    public static let ${name}: String = ${JSON.stringify(String(raw))}${comment}`,
          )
        }

        const sections = [
          'public extension Color {',
          ...colors,
          '}',
          '',
          'public enum CreouiTokens {',
          ...dimensions,
          ...(dimensions.length && numbers.length ? [''] : []),
          ...numbers,
          ...((dimensions.length || numbers.length) && strings.length ? [''] : []),
          ...strings,
          '}',
          '',
        ].join('\n')

        return `${header}\n${sections}`
      },
    },
  },
  platforms: {
    swift: {
      transforms: ['name/camel'],
      buildPath: 'packages/swift/Sources/Creoui/Generated/',
      files: [
        {
          destination: 'Tokens.swift',
          format: 'swift/creoui',
        },
      ],
    },
  },
}
